services:
  zupit_database:
    image: postgres
    environment:
      POSTGRES_USER: root 
      POSTGRES_DB: zupit_db
      POSTGRES_PASSWORD: root 
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  zupit_app:
    image: zupit_app 
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - zupit_database
    environment:
      DATABASE_URL: postgresql+psycopg://root:root@zupit_database:5432/app_db
volumes:
  pgdata:
